name: Deploy StatusTool Extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'app/StatusTool/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Check required secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Checking for required secrets..."
          if [ -z "${DOCKER_USERNAME}" ]; then
            echo "::error::DOCKER_USERNAME is empty"
            exit 1
          fi
          if [ -z "${DOCKER_PASSWORD}" ]; then
            echo "::error::DOCKER_PASSWORD is empty"
            exit 1
          fi
          echo "All required secrets are present"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        id: prepare
        working-directory: app/StatusTool
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/gpx-status
          VERSION=latest
          
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          
          TAGS="--tag ${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS --tag ${DOCKER_IMAGE}:latest"
          fi
          
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "buildx_args=\
            --build-arg IMAGE_NAME='gpx-status' \
            --build-arg AUTHOR='${{ github.actor }}' \
            --build-arg MAINTAINER='${{ github.repository_owner }}' \
            --build-arg MAINTAINER_EMAIL='maintainer@example.com' \
            --build-arg REPO='${{ github.repository }}' \
            --build-arg OWNER='${{ github.repository_owner }}' \
            --cache-from 'type=local,src=/tmp/.buildx-cache' \
            --cache-to 'type=local,dest=/tmp/.buildx-cache' \
            ${TAGS} \
            --file './Dockerfile' ." >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Cache Docker layers
        uses: actions/cache@v4
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-gpx-status-${{ hashFiles('app/StatusTool/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-gpx-status-${{ hashFiles('app/StatusTool/Dockerfile') }}
            ${{ runner.os }}-buildx-gpx-status

      - name: Pull latest image for cache
        run: |
          docker pull --platform 'linux/arm64/v8' ${{ steps.prepare.outputs.docker_image }}:latest || true

      - name: Docker Buildx (build)
        working-directory: app/StatusTool
        run: |
          docker buildx build \
            --output "type=image,push=false" \
            --platform 'linux/arm64/v8' \
            ${{ steps.prepare.outputs.buildx_args }}

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Buildx (push)
        if: success()
        working-directory: app/StatusTool
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform 'linux/arm64/v8' \
            ${{ steps.prepare.outputs.buildx_args }}

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}

      - name: Create image artifact
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        working-directory: app/StatusTool
        run: |
          GIT_HASH_SHORT=$(git rev-parse --short "$GITHUB_SHA")
          docker buildx build \
            ${{ steps.prepare.outputs.buildx_args }} \
            --platform "linux/arm64/v8" \
            --tag ${{ steps.prepare.outputs.docker_image }}:${GIT_HASH_SHORT} \
            --output "type=docker,dest=gpx-status-${GIT_HASH_SHORT}-arm64-v8.tar"

      - name: Upload artifact arm64-v8
        uses: actions/upload-artifact@v4
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        with:
          name: gpx-status-docker-image-arm64-v8
          path: 'app/StatusTool/*arm64-v8.tar'
          overwrite: true

      - name: Upload docker image for release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/') && success()
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'app/StatusTool/*.tar'
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: true
          file_glob: true