name: Deploy StatusTool Extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'app/StatusTool/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "Error: DOCKER_USERNAME secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Error: DOCKER_PASSWORD secret is not set"  
            exit 1
          fi

      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create required directories
        run: |
          mkdir -p app/StatusTool/static
          mkdir -p app/StatusTool/config
          mkdir -p app/StatusTool/templates
          touch app/StatusTool/CMakeLists_docker.txt
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app/StatusTool
          platforms: linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/gpx-status:latest
            ${{ secrets.DOCKER_USERNAME }}/gpx-status:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Job Summary
        if: always()
        run: |
          echo "### Build Status :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "* Image: ${{ secrets.DOCKER_USERNAME }}/gpx-status" >> $GITHUB_STEP_SUMMARY
          echo "* Tags: latest, ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "* Platforms: linux/arm64, linux/arm/v7" >> $GITHUB_STEP_SUMMARY