name: Deploy GPX StatusTool Extension

on:
  push:
    paths:
      - 'app/StatusTool/**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy BlueOS Extension
        uses: BlueOS-community/Deploy-BlueOS-Extension@v1
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: 'gpx-status'
          dockerfile-location: './app/StatusTool'